config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'books#index'
  resources :books
  resources :authors
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :age, presence: true, numericality: true

  has_many :authorships
  has_many :books, through: :authorships
end

app/models/authorship.rb
class Authorship < ApplicationRecord
  belongs_to :author
  belongs_to :book
end

app/models/book.rb
class Book < ApplicationRecord
  validates :title, presence: true
  validates :author, presence: true
  validates :genre, presence: true
  validates :classification, presence: true
  validates :year, presence: true, numericality: true

  has_many :authorships
  has_many :authors, through: :authorships

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController

  def index
    @authors = if params[:term]
      Author.where('first_name LIKE ? OR last_name LIKE ? OR age = ?',
      "%#{params[:term]}%", "%#{params[:term]}%", "#{params[:term].to_i}")
    else
      Author.all
    end
  end

  def new
    @author = Author.new
  end

  def create
    @author = Author.new(author_params)

    if @author.save
      redirect_to root_path, notice: 'Author successfully created.'
    else
      render :new, alert: '<strong>Could not save</strong> invalid data.'
    end
  end

  def show
    @author = Author.find(params[:id])
  end

  def edit
    @author = Author.find(params[:id])
  end

  def update
    @author = Author.find_by(id: params[:id])

    if @author && @author.update_attributes(book_params)
      redirect_to root_path
    else
      render 'edit'
    end
  end

  def destroy
    @author = Author.find_by(id: params[:id])

    if @author
      @author.destroy
      redirect_to root_path, notice: 'Author successfully deleted'
    else
      redirect_to root_path, alert: 'AuthorS does not exist'
    end
  end

  private

  def author_params
    params.require(:author).permit(:first_name, :last_name, :age, :term)
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @books = if params[:term]
      Book.where('title LIKE ? OR author LIKE ? OR genre LIKE ? OR classification LIKE ? OR year = ?',
      "%#{params[:term]}%", "%#{params[:term]}%", "%#{params[:term]}%", "%#{params[:term]}%", "#{params[:term].to_i}")
    else
      Book.all
    end
  end

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)

    if @book.save
      redirect_to root_path, notice: 'Book successfully created.'
    else
      render :new, alert: '<strong>Could not save</strong> invalid data.'
    end
  end

  def show
    @book = Book.find(params[:id])
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find_by(id: params[:id])

    if @book && @book.update_attributes(book_params)
      redirect_to root_path
    else
      render 'edit'
    end
  end

  def destroy

    #raise params

    @book = Book.find_by(id: params[:id])

    if @book
      @book.destroy
      redirect_to root_path, notice: 'Book successfully deleted'
    else
      redirect_to root_path, alert: 'Book does not exist'
    end
  end

  private

  def book_params
    params.require(:book).permit(:title, :author, :genre, :classification, :year, :term)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/authors/edit.html.erb
<div class="booyah-box col-10 offset-1">
  <h1>Edit Author Info</h1>
  <%= simple_form_for @author do |f| %>
    <%= f.input :first_name %>
    <%= f.input :last_name %>
    <%= f.input :age %>
    <br />
    <%= f.submit 'Add Author', class: 'btn btn-primary' %>
  <% end %>
</div>
<br />
<br />
<%= link_to 'Remove Author', book_path(@author), :method => :delete, class: 'btn btn-danger' %>

app/views/authors/index.html.erb
<div class="booyah-box col-10 offset-1">

  <%= form_tag(authors_path, method: :get) do %>
    <%= text_field_tag :term %>
    <%= submit_tag 'Search', name: nil %>
  <% end %>

  <% @authors.each  do | author | %>
    <div>
      <h1> <%= link_to "#{author.first_name} #{author.last_name}", author_path(author) %></h1>
    </div>
    <hr />
  <% end %>

</div>

app/views/authors/new.html.erb
<div class="booyah-box col-10 offset-1">
  <h1>Enter New Author Info</h1>
  <%= simple_form_for @author do |f| %>
    <%= f.input :first_name %>
    <%= f.input :last_name %>
    <%= f.input :age %>
    <br />
    <%= f.submit 'Add Author', class: 'btn btn-primary' %>
  <% end %>
</div>

app/views/authors/show.html.erb
<div class="booyah-box col-10 offset-1">
  <% author = Author.find(@author.id) %>
  <h1><%= "Books by #{author.first_name} #{author.last_name}:" %></h1>
  <% author.books.each do |book| %>
    <%= link_to book.title, book_path(book) %>
  <% end %>
</div>

app/views/books/edit.html.erb
<div class="booyah-box col-10 offset-1">
  <h1>Edit Book Info</h1>
  <%= simple_form_for @book do |f| %>
    <%= f.input :title %>
    <%= f.input :genre %>
    <%= f.input :classification, label: "Classification (Fiction/Nonfiction/etc)" %>
    <%= f.input :year %>
    <br />
    <%= f.submit 'Edit Book', class: 'btn btn-primary' %>
  <% end %>
<br />
<br />
  <%= link_to 'Remove Book', book_path(@book), :method => :delete, class: 'btn btn-danger' %>
</div>

app/views/books/index.html.erb
<div class="booyah-box col-10 offset-1">

  <%= form_tag(books_path, method: :get) do %>
    <%= text_field_tag :term %>
    <%= submit_tag 'Search', name: nil %>
  <% end %>

  <% @books.each  do | book | %>
    <div>
      <h1> <%= link_to book.title, book_path(book) %></h1>
      <h6>- <%= book.genre %></h6>
      <h6>- <%= book.classification %></h6>
      <h6>- <%= book.year %></h6>
      <h6> <%= link_to 'Edit Book', edit_book_path(book) %> </h6>
    </div>
    <hr />
  <% end %>

</div>

app/views/books/new.html.erb
<div class="booyah-box col-10 offset-1">
  <h1>Enter New Book Info</h1>
  <%= simple_form_for @book do |f| %>
    <%= f.input :title %>
    <%= f.input :genre %>
    <%= f.input :classification, label: "Classification (Fiction/Nonfiction/etc)" %>
    <%= f.input :year %>
    <br />
    <%= f.submit 'Add Book', class: 'btn btn-danger' %>
  <% end %>
</div>

app/views/books/show.html.erb
<div class="booyah-box col-10 offset-1">
  <% book = Book.find(@book.id) %>
  <h1> <%= book.title %></h1>
  <h3><%= "Written by: " %> </h3>
  <% book.authors.each do |author| %>
    <h3> <%= link_to "#{author.first_name} #{author.last_name}", author_path(author) %> </h3>
  <% end %>
  <h6>- <%= book.genre %></h6>
  <h6>- <%= book.classification %></h6>
  <h6>- <%= book.year %></h6>
  <h6> <%= link_to 'Edit Book', edit_book_path(book) %> </h6>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookshelf</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

    <header class="row">
      <div class="col-3">
        <%= link_to 'Your Catalog', root_path %>
      </div>
      <div class="col-3">
        <%= link_to 'Your Authors', authors_path %>
      </div>
      <div class="col-3">
        <%= link_to 'New Book', new_book_path %>
      </div>
      <div class="col-3">
        <%= link_to 'New Author', new_author_path %>
      </div>
    </header>

  <body>

    <% if flash[:error].present? %>
      <div class="col-10 offset-1 alert alert-danger">
        <%= flash[:error].html_safe %>
      </div>
    <% end %>

    <%= yield %>
  </body>
</html>